### ISSUE TITLE
The budgie appmenu thing is kind of ugly because it's stuck together?

### ISSUE THREAD

**Issue by SolarAquarion** [rilian-la-te/vala-panel-appmenu#86] opened 2017-05-15 14:03 UTC
![screenshot_2017-05-15_10-02-57](https://cloud.githubusercontent.com/assets/5307016/26061368/c4ded5a0-3955-11e7-8e2b-d0e005957ec5.png)

**Comment by SolarAquarion** [comment] 2017-05-15 14:10
i was using the built in theme then

**Comment by rilian-la-te** [comment] 2017-05-15 14:47
Duplicate of [#69](https://github.com/rilian-la-te/vala-panel-appmenu/issues/69)?

**Comment by rilian-la-te** [comment] 2017-05-15 14:48
If yes, close this:)

**Comment by SolarAquarion** [comment] 2017-05-15 15:22
@rilian-la-te Well, one way to bypass it is to disable native theme

**Comment by rilian-la-te** [comment] 2017-05-15 15:30
native (desktop) or builtin (inside Budgie)?

**Comment by SolarAquarion** [comment] 2017-05-15 15:30
Builtin

**Comment by rilian-la-te** [comment] 2017-05-15 15:32
Menus are transparent?

**Comment by SolarAquarion** [comment] 2017-05-15 15:32
Yes

**Comment by rilian-la-te** [comment] 2017-05-15 15:33
So, this is #69. Try to build latest Budgie master, please, This will closed as duplicate.

**Closed by rilian-la-te** 2017-05-15 15:33 UTC
Labels: bug

**Comment by SolarAquarion** [comment] 2017-05-15 15:36
I have budgie desktop git on my desktop

**Comment by rilian-la-te** [comment] 2017-05-15 15:47
Reopened #69

**Comment by rilian-la-te** [comment] 2017-05-15 15:48
Install latest master of appmenu, please.

**Comment by rilian-la-te** [comment] 2017-05-15 15:52
See #69 for futher instructions

**Comment by SolarAquarion** [comment] 2017-05-15 15:52
38%] Linking C static library libvala-dbusmenu.a
[ 38%] Built target vala-dbusmenu
[ 40%] Generating appmenu-bamf.c;appmenu-desktop.c;registrar.c;menubar.c;menu-widget.c;menu-widget-dbusmenu.c;menu-widget-menumodel.c;/home/solaraquarion/build/vala-panel-appmenu-xfce-git/src/vala-panel-appmenu/vapi/config.c;vala-panel-appmenu.vapi;vala-panel-appmenu.h
error: Package `vala-dbusmenu' not found in specified Vala API directories or GObject-Introspection GIR directories
Compilation failed: 1 error(s), 0 warning(s)
make[2]: *** [lib/CMakeFiles/appmenu-core.dir/build.make:99: lib/appmenu-core_valac.stamp] Error 1
make[1]: *** [CMakeFiles/Makefile2:719: lib/CMakeFiles/appmenu-core.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

**Comment by rilian-la-te** [comment] 2017-05-15 16:13
Try latest master

**Comment by rilian-la-te** [comment] 2017-05-15 16:16
Really, try:)

**Comment by SolarAquarion** [comment] 2017-05-15 16:17
Fixes the build
