### ISSUE TITLE
Pull down menus are local, not global, in the MATE applet

### ISSUE THREAD

**Issue by flexiondotorg** [rilian-la-te/vala-panel-appmenu#216] opened 2018-03-02 14:55 UTC
If I use a keybinding to activate a menu, for example `Alt` + `f`, the application pull down menu is displayed, not the global menu. The rendering of the separators is also incorrect.

![pull-down-menus-are-local](https://user-images.githubusercontent.com/304639/36904621-11701e70-1e29-11e8-81cb-0a451ddb635d.png)

This was tested on Ubuntu MATE 18.04 daily and vala-panel-appmenu 0.6.92 with appmenu-gtk-module 0.6.92.

**Comment by rilian-la-te** [comment] 2018-03-02 23:41
About pulldown - I currently do not know how to fix it, because it was in all releases of vala-panel-appmenu, and it is rendered not by applet, but by application 's hidden menubar. I can try to remove it altogether, but we need a custom WM for catching it (Unity was a custom WM).

**Comment by rilian-la-te** [comment] 2018-03-03 00:13
Duplicate of #165. Closing, sorry.

**Closed by rilian-la-te** 2018-03-03 00:13 UTC
