### ISSUE TITLE
Global Menus work with "everything" except Firefox and Thunderbird

### ISSUE THREAD

**Issue by flexiondotorg** [rilian-la-te/vala-panel-appmenu#125] opened 2017-08-15 15:44 UTC
Following on from https://github.com/rilian-la-te/vala-panel-appmenu/issues/124 some testing now reveals that GTK2+, GTK3+ and Qt applications work with Global Menu regardless how they are launched. Chrome, Chromium and Electron applications (Skype and Visual Studio Code were tested) also work with Global Menu.

However, Firefox and Thunderbird are no longer showing a global menu and Audacity will only show a global menu if launched from a terminal with:

    env UBUNTU_MENUPROXY=1 audacity

However, `UBUNTU_MENUPROXY` is exported in the session. @rilian-la-te Any ideas?

**Comment by rilian-la-te** [comment] 2017-08-15 15:46
Firefox and Thunderbird is your property, because it is Ubuntu-only issues. Maybe a patch was reversed, look to it, please. For me it always non-working (I am an Archer).
About audacity - will test it at home.

**Comment by rilian-la-te** [comment] 2017-08-15 15:47
For now, it is duplicate of https://github.com/rilian-la-te/vala-panel-appmenu/issues/17 , I think.

**Comment by rilian-la-te** [comment] 2017-08-15 15:49
Audacity works for me (OpenSUSE, modified MATE 1.18)

**Comment by flexiondotorg** [comment] 2017-08-15 16:17
Firefox and Thunderbird are both still carrying the AppMenu patches in Ubuntu.

**Comment by rilian-la-te** [comment] 2017-08-15 16:20
Ok, what protocol audacuty used? Appmenu or dbusmenu?

**Comment by flexiondotorg** [comment] 2017-08-15 17:43
So, we can forget about audacity in Ubuntu. I found this in their .desktop file:

    Exec=env UBUNTU_MENUPROXY=0 audacity %F

I'll find out what is going on with that.

**Comment by rilian-la-te** [comment] 2017-08-15 17:51
What about Firefox and Thunderbird? Do it have GTK AppMenu properties. If have, I know how to fix a bug.

**Comment by flexiondotorg** [comment] 2017-08-15 20:41
Yes, I believe so because they display global menus on 17.10 using Unity 7.

**Comment by rilian-la-te** [comment] 2017-08-15 22:04
But what about KDE? They have menus in KDE?

**Comment by flexiondotorg** [comment] 2017-08-16 12:47
Are you asking if FF/TB have Global Menus in KDE or if just the menus are available?

**Comment by rilian-la-te** [comment] 2017-08-16 12:48
Yes, about Global Menus in KDE (5.9 minimal)

**Comment by flexiondotorg** [comment] 2017-08-22 23:05
I have used KDE for about over 10 years, I can't help test KDE. Sorry :-( However, attached is a screenshot of Firefox from Ubuntu 17.10 to show that the "Unity menus" are available and enabled by default.

![firefox-ubuntu-1710](https://user-images.githubusercontent.com/304639/29591409-541bf278-8796-11e7-85b2-b767fbc62ab6.png)

This is the patch that is applied to Firefox in Ubuntu that add menubar support:

  * http://bazaar.launchpad.net/~mozillateam/firefox/firefox-trunk.head/view/head:/debian/patches/unity-menubar.patch

**Comment by rilian-la-te** [comment] 2017-08-23 05:07
@flexiondotorg, I am Pugin, not Putin. Please, fix description in upstream unity-gtk-module.

**Comment by rilian-la-te** [comment] 2017-08-23 05:56
do you have gtk dbusmenu packages installed?

**Comment by flexiondotorg** [comment] 2017-08-23 10:22
I'll get your name corrected. Very sorry about that typo 🙁

**Comment by rilian-la-te** [comment] 2017-08-23 10:26
do you have gtk dbusmenu packages installed?

**Comment by flexiondotorg** [comment] 2017-08-23 10:27
Yes, I have the dbusmenu gtk packages installed. They are all listed as install dependencies in the `vala-panel-appmenu ` packages.

**Comment by rilian-la-te** [comment] 2017-08-23 10:28
Tried XDG_CURRENT_DESKTOP=Unity?

**Comment by rilian-la-te** [comment] 2017-08-23 10:44
do you have vala-panel-appmenu on LiveCD by default?

**Comment by flexiondotorg** [comment] 2017-08-23 11:46
I have tried `env XDG_CURRENT_DESKTOP=Unity firefox` and it made no difference.

Yes, the Ubuntu MATE 17.10 daily image is a live session. 

  * http://cdimage.ubuntu.com/ubuntu-mate/daily-live/current/

When you are at the MATE Desktop use `mate-tweak` to enable either the *Cupertino*, *Contemporary* or *Mutiny* panel layouts to enable `vala-panel-appmenu`.

**Comment by rilian-la-te** [comment] 2017-08-24 06:47
Firefox in Artful wants ```UBUNTU_MENUPROXY=0```
try ```UBUNTU_MENUPROXY=0 firefox``` in console.

**Comment by rilian-la-te** [comment] 2017-08-28 07:21
Please, try set ```UBUNTU_MENUPROXY=0``` for XUL apps. It works for me.

**Comment by flexiondotorg** [comment] 2017-08-28 08:46
I confirm that setting `UBUNTU_MENUPROXY=0` for Firefox and Thunderbird works. I've spoken to the Ubuntu Desktop team and understand why this counter intuitive requirement exists and Ubuntu MATE 17.10 now includes the appropriate configuration by default. Thanks for your help @rilian-la-te.

**Closed** 2017-08-28 08:47 UTC
Labels: bug, ubuntu

**Comment by rilian-la-te** [comment] 2017-08-28 10:09
can you provide info about this requirement here?
