### ISSUE TITLE
jayatana

### ISSUE THREAD

**Issue by PHPJosh** [rilian-la-te/vala-panel-appmenu#122] opened 2017-08-05 00:17 UTC
Just wondering if jayatana is included in the Arch AUR package appmenu-gtk-module-git and if not do you plan on adding jayatana to the AUR package or plan to add one for jayatana? just wondering

**Comment by rilian-la-te** [comment] 2017-08-05 05:17
Jayatana is expeimental now, you can use it in your own risk, so, no package.

**Comment by PHPJosh** [comment] 2017-08-05 17:42
alright

**Comment by rilian-la-te** [comment] 2017-08-09 14:01
Closed as duplicate of https://github.com/rilian-la-te/vala-panel-appmenu/issues/115

**Closed by rilian-la-te** 2017-08-09 14:02 UTC
