### ISSUE TITLE
Applet stops receive events after focus stealed from window with opened applet menu

### ISSUE THREAD

**Issue by nick87720z** [rilian-la-te/vala-panel-appmenu#156] opened 2017-12-15 09:54 UTC
Problem happens when global menu is opened for some window, and another window appears at this moment (many reason... either some app took too long to launch, so you are tired to wait, or some warning dialog). Once, new window appears, applet stops to react for mouse, though visually it still updates (on window change). It doesn't make sense, what menu was opened - main menu bar or gtk3 header bar menu.
current git state: 23c94cd
with xfce4-panel, for now 4.13 (but such problem appeared with 4.12 too)

Previous state was 982a163 (build date 25.06.2017): that time event reaction did not break until i switch from new appeared window to any other. And when was caused by active headerbar menu, only it's submenu item was blocked, main menubar still worked.

**Comment by rilian-la-te** [comment] 2017-12-15 11:52
Can you determine exact commit which causes it?
And tell me a distro, please. And behaviour with other WMs and panels.

**Comment by nick87720z** [comment] 2017-12-15 15:18
With vala-panel this problem doesn't happen.
With xfce4-panel i tried xfwm4, gala, compiz - they do nothing with this (and wm restart doesn't solve problem, only panel or plugin restart).
Exact xfce4-panel version - 4.13.1.

**Comment by rilian-la-te** [comment] 2017-12-15 19:00
Yes:-) AFAIK this was written for vala-panel :-))

**Comment by nick87720z** [comment] 2017-12-17 21:41
I got single case, when this bug did not work, but next time i could not reproduce it. This time, runing panel from terminal, i got these gtk errors, after lock came. For test i used leafpad instances. First is started manually, second - from terminal with `$ sleep 6; leafpad`

When second leafpad starts (menu from first one is opened):
`(wrapper-2.0:622): Gtk-CRITICAL **: gtk_window_set_mnemonics_visible: assertion 'GTK_IS_WINDOW (window)' failed`
Switching to terminal
`(wrapper-2.0:622): Gtk-CRITICAL **: gtk_widget_get_toplevel: assertion 'GTK_IS_WIDGET (widget)' failed` (many times)
Mouse over menubar... (per each event)
`(wrapper-2.0:622): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed`
One time, during mouse over, i got this line, but still don't understand, what movement exactly triggers it:
`(wrapper-2.0:622): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed`

**Comment by rilian-la-te** [comment] 2017-12-17 22:11
Widget is incorrectly working, it is strange. But with vala-panel?

**Comment by nick87720z** [comment] 2017-12-18 17:36
vala-panel is ok, problem appears only with xfce4-panel.
For now i have these two installed. Would be good if someone tests with mate too.

**Comment by rilian-la-te** [comment] 2017-12-18 19:50
Mate should be tested in and out of process, because vala-panel is only in, xfce4-panel is only out of process.

**Comment by nick87720z** [comment] 2018-01-06 03:27
I could reproduce it with both other panels too. Problem in mate-panel - it somehow inhibits all gtk warnings, only writing own. But behavior is same. For all panels, there is one change: when focus is stealed, opened submenu doesn't even disappear, but loses focus, and can't get it anymore. So, all desktop may be used, besides that this submenu covers some part of desktop with all windows. And applet with this submenu is unresponsible visually.

After bug is triggered, moving mouse over menubar produces error for each move event:
`(vala-panel:21387): Gtk-CRITICAL **: gtk_widget_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed`
And for submenu it is:
`(vala-panel:21387): Gtk-CRITICAL **: gtk_window_set_mnemonics_visible: assertion 'GTK_IS_WINDOW (window)' failed`

**Comment by rilian-la-te** [comment] 2018-01-06 09:41
But for me vala-panel is working after focus stealing, just with floating menu.

**Comment by rilian-la-te** [comment] 2018-01-24 02:32
Try to reproduce now, please.

**Comment by nick87720z** [comment] 2018-01-24 03:02
Hello, sorry for long time without reaction... busy studying in urfu, will get as soon as possible.

**Comment by nick87720z** [comment] 2018-02-01 09:00
No blocks anymore.
When window changes, menu syncs, but is still opened, so navigation is not interrupted.

**Comment by nick87720z** [comment] 2018-02-01 09:03
Don't know, could it be caused by buggy glib, but this is after glib update to now stabilized 2.52

**Comment by rilian-la-te** [comment] 2018-02-01 09:14
No, it is because now I moved to another menubar approach)

**Comment by rilian-la-te** [comment] 2018-02-01 09:14
Closing this)

**Closed by rilian-la-te** 2018-02-01 09:14 UTC
Labels: XFCE, bug
