### ISSUE TITLE
Wanting to use XFCE4 Panel in Openbox

### ISSUE THREAD

**Issue by Dobbie03** [rilian-la-te/vala-panel-appmenu#42] opened 2017-01-03 02:15 UTC
but the module fails to load:

Gtk-Message: Failed to load module "topmenu-gtk-module" 

Does this only work in XFCE?

**Comment by rilian-la-te** [comment] 2017-01-03 12:53
Topmenu is not my module. My project needs unity-gtk-module:) You are confused with another project. Any questions?

**Comment by rilian-la-te** [comment] 2017-03-29 12:15
Not a bug, closing.

**Closed by rilian-la-te** 2017-03-29 12:15 UTC
