### ISSUE TITLE
In Firefox and Thunderbird the dropdown menus are empty

### ISSUE THREAD

**Issue by cgiannakidis70** [rilian-la-te/vala-panel-appmenu#212] opened 2018-02-24 19:26 UTC
I dont know if this is issued again but as you can see in the attached picture the dropdown menus in firefox and thunderbird are empty.
OS Xubuntu 18.04
I installed following the instructions in README exactly.(master branch)
![screenshot_2018-02-24_21-19-54](https://user-images.githubusercontent.com/33185625/36634157-ee8445b4-19a8-11e8-9e17-b6af98677a72.png)

**Comment by rilian-la-te** [comment] 2018-02-24 19:34
It is an Ubuntu-only. I cannot see how to fix this. Do KDE has this problem? And what version are you have?

**Comment by cgiannakidis70** [comment] 2018-02-24 19:42
I am sorry but I don't know about KDE.I am using xubuntu 18.04 (xfce4)
I installed with git from master branch as described in README file.

**Comment by rilian-la-te** [comment] 2018-02-24 19:51
On another Qt applications, chromium or Electron issue happens?

**Comment by cgiannakidis70** [comment] 2018-02-24 20:01
I tried  Chrome but appmenu works fine .
Please list some qt apps so I can try them.

**Comment by rilian-la-te** [comment] 2018-02-24 20:05
Electron : Atom, Skype, VSCode
Qt: QtCreator, audacious (Qt)

**Comment by cgiannakidis70** [comment] 2018-02-24 20:19
Skype is working fine also Audacious and QtCreator.

**Comment by rilian-la-te** [comment] 2018-02-24 20:21
Do firefox working after alt-tab?

**Comment by cgiannakidis70** [comment] 2018-02-24 20:35
You mean to press alt-tab and then check the dropdown menus.No, I am afraid that it is not working either.

**Comment by rilian-la-te** [comment] 2018-02-24 20:43
Do you have a d-feet?

**Comment by cgiannakidis70** [comment] 2018-02-24 20:49
well I installed d-feet from Software app.Now what ?

**Comment by rilian-la-te** [comment] 2018-02-24 20:53
Now you need to search for firefox in d-feet and do some Requests as Importer do.

**Comment by rilian-la-te** [comment] 2018-02-24 21:02
You need to request GetLayout with parameters 0,1 and show me an output here.

**Comment by cgiannakidis70** [comment] 2018-02-24 21:14
Could you be more clear?
How to syntax GetLayout request?
See the picture.
![screenshot_2018-02-24_23-13-10](https://user-images.githubusercontent.com/33185625/36635133-5ea3351c-19b8-11e8-8496-82158fa84d50.png)

**Comment by rilian-la-te** [comment] 2018-02-24 21:17
```0,1,['type','children-display','label']```

**Comment by cgiannakidis70** [comment] 2018-02-24 21:24
9,
(2,
 {'children-display': 'submenu', 'label': '_File'},
 [(3, {'label': 'Label Empty'}, [])])

**Comment by rilian-la-te** [comment] 2018-02-24 21:26
So, this is your empty menu. Can you now request AboutToShow  from 2?

**Comment by cgiannakidis70** [comment] 2018-02-24 21:28
False

**Comment by rilian-la-te** [comment] 2018-02-24 21:28
And GetLayout then

**Comment by cgiannakidis70** [comment] 2018-02-24 21:30
One minute.I am lost."False" is the output for the "AboutToShow" request for "2".What next?

**Comment by rilian-la-te** [comment] 2018-02-24 21:32
repeat GetLayout for 2

**Comment by cgiannakidis70** [comment] 2018-02-24 21:33
9,
(2,
 {'children-display': 'submenu', 'label': '_File'},
 [(3, {'label': 'Label Empty'}, [])])

**Comment by rilian-la-te** [comment] 2018-02-24 21:35
so, we need an Ubuntu-only firefox hack.

**Comment by rilian-la-te** [comment] 2018-02-24 21:38
Can you write some patches for this yourself? I does not have Ubuntu now. And cannot debug Unity firefox, sorry.

**Comment by rilian-la-te** [comment] 2018-02-24 21:39
But if this bug can be reproduced on Arch, I will fix it ASAP.

**Comment by cgiannakidis70** [comment] 2018-02-24 21:44
I'm glad that I help.I'm not sure that i could write any patch.Anyway I'll wait for your fix.
Thanks  a lot.

**Comment by rilian-la-te** [comment] 2018-02-24 21:47
I will try to fix it, but cannot sure than I can.

**Comment by rilian-la-te** [comment] 2018-02-24 21:51
@lestcape can you help me with some Ubuntu info? Do AboutToShow hack works with new Ubuntu firefox (18.04)?
And if not, which works?

**Comment by lestcape** [comment] 2018-02-25 02:41
@rilian-la-te I don't know. I have not 18.04 yet. I just have 16.04... Probably i never install 18.04 until it will be released. The ubuntu alpha/beta are always a pain. It's not like arch where more-less, the system seem to be usable.

**Comment by rilian-la-te** [comment] 2018-02-25 03:10
@lestcape if you have quantum firefox backported, 18.04 is not required. I just need to know about AboutToShow hack of quantum firefox on Ubuntu.

**Comment by rilian-la-te** [comment] 2018-02-25 04:24
Thanks.

**Comment by rilian-la-te** [comment] 2018-02-25 04:38
https://bugs.launchpad.net/plasma-widget-menubar/+bug/878165

**Comment by cgiannakidis70** [comment] 2018-02-25 11:02
Hi there.
I installed firefox quantum 59 b from next ppa and now the appmenu displays only the app name for firefox without the global menu.I did the workaround from hints for firefox but it does not work.

**Comment by rilian-la-te** [comment] 2018-02-25 11:58
It may not have Unity patch. And it is not supported, because patch is Ubuntu thing and Ubuntu can drop it in any time.

**Comment by flexiondotorg** [comment] 2018-02-26 20:55
Firefox in Ubuntu carries appmenu patches. You have to be running Firefox from Ubuntu for it to work with vala-panel-appmenu. 

That said, Firefox in Ubuntu worked with vala-panel-appmenu 0.6.1 but it has regressed in 0.6.92 and now all menus are empty.

**Comment by rilian-la-te** [comment] 2018-02-26 21:29
Will look for it. If Unity patch is carried, it should work. But I cannot test it.

**Comment by cgiannakidis70** [comment] 2018-03-02 17:42
Hi there again.I have noticed that the dropdown menus appear if i use the "ALT " and the key for a menu and then cycle between another window and back to firefox .Of course this possibility disappears if I restart the xfce4-panel.

**Comment by flexiondotorg** [comment] 2018-03-03 02:41
Yes, I will test tomorrow.

**Comment by flexiondotorg** [comment] 2018-03-03 03:04
I rebuilt 0.9.62 with https://github.com/rilian-la-te/vala-panel-appmenu/commit/723a7b1fe42c457ff5d0e1664aa2845f0a2ab699 and https://github.com/rilian-la-te/vala-panel-appmenu/commit/78eb84760b58022beaa7d6b061c3406d11e1b529 patches applied. Sadly, no change. Firefox and Thunderbird menus are still empty.

**Comment by rilian-la-te** [comment] 2018-03-03 03:05
Ok, will look for it. It will be difflicult without ability to test it.

**Closed** 2018-03-03 03:46 UTC
Labels: ubuntu

**Comment by flexiondotorg** [comment] 2018-03-03 22:08
@rilian-la-te Thank you for working on this. It works a treat :smile:

**Comment by cgiannakidis70** [comment] 2018-03-03 23:25
@rilian-la-te Thank you for fix.
